[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "faiss-cpu>=1.12.0",
    "fastapi>=0.121.2",
    "ipykernel>=7.1.0",
    "langchain>=1.0.7",
    "langchain-community>=0.4.1",
    "langchain-huggingface>=1.0.1",
    "lxml>=6.0.2",
    "openai>=2.8.0",
    "pdfminer>=20191125",
    "pdfminer-six==20201018",
    "pi-heif>=1.1.1",
    "pillow>=12.0.0",
    "psycopg2>=2.9.11",
    "pydantic>=2.12.4",
    "pymupdf>=1.26.6",
    "pypdf>=6.2.0",
    "pytesseract>=0.3.13",
    "python-dotenv>=1.2.1",
    "python-multipart>=0.0.20",
    "sentence-transformers>=5.1.2",
    "setuptools>=80.9.0",
    "streamlit>=1.51.0",
    "supabase>=2.24.0",
    "unstructured>=0.18.20",
    "uvicorn>=0.38.0",
    "wheel>=0.45.1",
]
